# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
