image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~tristan957/dotfiles
tasks:
  - download: |
      cd dotfiles
      nix develop --command true
  - check-flake: |
      cd dotfiles
      nix flake check
  - check-postgres-flake: |
      cd dotfiles/flakes/postgres
      nix flake check
