image: alpine/edge
packages:
  - reuse
  - ruff
  - shellcheck
  - shfmt
  - stylua
  - yarn
sources:
  - https://git.sr.ht/~tristan957/dotfiles
tasks:
  - reuse: |
      cd dotfiles
      reuse lint
  - ruff: |
      cd dotfiles
      ./scripts/ruff.sh
  - shellcheck: |
      cd dotfiles
      ./scripts/shellcheck.sh
  - shfmt: |
      cd dotfiles
      ./scripts/shfmt.sh
  - stylua: |
      cd dotfiles
      stylua --check .
  - yarn: |
      cd dotfiles
      yarn
  - prettier: |
      cd dotfiles
      yarn run prettier:check
  - markdownlint: |
      cd dotfiles
      yarn run markdownlint:check
