image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~tristan957/dotfiles
tasks:
  - reuse: |
      cd dotfiles
      nix develop --command reuse lint
  - luacheck: |
      cd dotfiles
      nix develop --command luacheck .
  - ruff: |
      cd dotfiles
      nix develop --command ruff check --diff .
      nix develop --command ruff format --diff .
  - shellcheck: |
      cd dotfiles
      nix develop --command ./scripts/shellcheck.sh
  - shfmt: |
      cd dotfiles
      nix develop --command ./scripts/shfmt.sh
  - stylua: |
      cd dotfiles
      nix develop --command stylua --check .
  - prettier: |
      cd dotfiles
      nix develop --command prettier --config .prettierrc.yml --check '**/*.{yaml,yml}'
  - markdownlint: |
      cd dotfiles
      nix develop --command markdownlint-cli2 '**/*.md'
