image: alpine/edge
packages:
  - reuse
  - shellcheck
  - shfmt
  - stylua
sources:
  - https://git.sr.ht/~tristan957/dotfiles
tasks:
  - reuse: |
      cd dotfiles
      reuse lint
  - shfmt: |
      cd dotfiles
      ./scripts/shfmt.sh
  - stylua: |
      cd dotfiles
      stylua --check .
  - lint: |
      cd dotfiles
      shellcheck --shell bash --source-path bash -x bash/.bashrc \
        $(find . -name "*.sh" -print | grep --invert-match -F "git-prompt.sh" | xargs)
