#!/bin/sh

# The PostgreSQL mailing lists are completely stupid and don't use
# git-send-email(1). So what does that mean? It means that we have to use bat(1)
# to colorize patches because the content types of patches can literally be
# anything since all patches are sent as attachments in an email. BUT, because
# bat(1) uses Sublime TextMate theme files, and I don't have the time to write
# one, this script will check if the extension on the attachment is .patch or
# .diff and shell out to aerc's colorize. Otherwise, it will pass through to
# bat(1).

if [ "$#" -ne 1 ]; then
	echo "Missing filename."
fi

filename="$1"

case $filename in
  (.*.*) extension="${filename##*.}";;
  (.*)   extension="";;
  (*.*)  extension="${filename##*.}";;
  (*)    extension="";;
esac

if [ -z "$extension" ] || [ "$extension" = "diff" ] || [ "$extension" = "patch" ]; then
	colorize <"/dev/stdin"
else
	bat -fP --file-name="$filename" --style=plain <"/dev/stdin"
fi
