---@type PickerInterface
return {
  buffers = function() require("telescope.builtin").buffers() end,
  builtin = function() require("telescope.builtin").builtin() end,
  command_history = function() require("telescope.builtin").command_history() end,
  diagnostics = function() require("telescope.builtin").diagnostics() end,
  files = function() require("telescope.builtin").find_files() end,
  git_bcommits = function() require("telescope.builtin").git_bcommits() end,
  git_branches = function() require("telescope.builtin").git_branches() end,
  git_commits = function() require("telescope.builtin").git_commits() end,
  git_stash = function() require("telescope.builtin").git_stash() end,
  git_tags = function() end,
  ---@param globs string[]
  grep = function(globs)
    require("telescope.builtin").live_grep({
      additional_args = { "--hidden" },
      glob_pattern = globs,
    })
  end,
  help_tags = function() require("telescope.builtin").help_tags() end,
  highlights = function() require("telescope.builtin").highlights() end,
  jumplist = function() require("telescope.builtin").jumplist() end,
  keymaps = function() require("telescope.builtin").keymaps() end,
  loclist = function() require("telescope.builtin").loclist() end,
  loclist_history = function() end,
  lsp_declarations = function() require("telescope.builtin").lsp_definitions() end,
  lsp_definitions = function() require("telescope.builtin").lsp_definitions() end,
  lsp_document_symbols = function() require("telescope.builtin").lsp_document_symbols() end,
  lsp_implementations = function() require("telescope.builtin").lsp_implementations() end,
  lsp_incoming_calls = function() require("telescope.builtin").lsp_incoming_calls() end,
  lsp_outgoing_calls = function() require("telescope.builtin").lsp_outgoing_calls() end,
  lsp_references = function() require("telescope.builtin").lsp_references() end,
  lsp_type_definitions = function() require("telescope.builtin").lsp_type_definitions() end,
  lsp_workspace_symbols = function() require("telescope.builtin").lsp_dynamic_workspace_symbols() end,
  man_pages = function() require("telescope.builtin").man_pages() end,
  marks = function() require("telescope.builtin").marks() end,
  quickfix = function() require("telescope.builtin").quickfix() end,
  quickfix_history = function() require("telescope.builtin").quickfixhistory() end,
  registers = function() require("telescope.builtin").registers() end,
  resume = function() require("telescope.builtin").resume() end,
  search_history = function() require("telescope.builtin").search_history() end,
  tagstack = function() require("telescope.builtin").tagstack() end,
}
