#!/bin/sh

SIGNATURES_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/aerc/signatures"

case "$AERC_ACCOUNT" in
    Personal)
        case "$AERC_FOLDER" in
            Postgres/*)
                cat "$SIGNATURES_DIR/work.txt"
                ;;
            *)
                cat "$SIGNATURES_DIR/personal.txt"
                ;;
        esac
        ;;
    Work)
        cat "$SIGNATURES_DIR/work.txt"
        ;;
    *)
        cat "$SIGNATURES_DIR/personal.txt"
        ;;
esac
