confirmOnQuit: false
disableStartupPopups: true
git:
  pagers:
    - colorArg: always
      externalDiffCommand: difft --color=always
      pager: delta --paging=never
gui:
  nerdFontsVersion: "3"
os:
  editPreset: nvim
update:
  method: never
