confirmOnQuit: false
disableStartupPopups: true
git:
  diffRenderers:
    - command: delta --paging=never
      colorArg: always
    - command: difft --color=always
      type: extDiff
gui:
  nerdFontsVersion: "3"
os:
  editPreset: nvim
update:
  method: never
