require("tristan957.lualine")
require("tristan957.tree-sitter")
require("tristan957.lsp")
require("tristan957.telescope")
require("tristan957.nvim-compe")
require("tristan957.gitsigns")
require("tristan957.trouble")
require("tristan957.rust-tools")
