# Provide as the --extra-conf parameter to the nix installer

auto-optimise-store = true
use-xdg-base-directories = true

extra-substituters = https://cache.numtide.com
extra-trusted-public-keys = cache.numtide.com-1:GF3TabtFocLtonIGfz3PD61AgIO8GmjCYhEAmYy4VPY=
